# Generated by Django 4.0.1 on 2022-01-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wylot', models.CharField(max_length=32)),
                ('przylot', models.CharField(max_length=32)),
                ('data', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Rok',
        ),
    ]
