# Generated by Django 4.0.1 on 2022-01-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0002_loty_delete_rok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loty',
            old_name='data',
            new_name='data_lotu',
        ),
        migrations.RenameField(
            model_name='loty',
            old_name='przylot',
            new_name='lotnikso_przylot',
        ),
        migrations.RenameField(
            model_name='loty',
            old_name='wylot',
            new_name='lotnisko_wylot',
        ),
    ]
