# Generated by Django 4.0.1 on 2022-01-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0003_rename_data_loty_data_lotu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loty',
            old_name='lotnikso_przylot',
            new_name='lotnisko_przylot',
        ),
    ]
