# Generated by Django 4.0.1 on 2022-01-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0004_rename_lotnikso_przylot_loty_lotnisko_przylot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loty',
            options={'verbose_name': 'Lot', 'verbose_name_plural': 'Loty'},
        ),
    ]
