# Generated by Django 4.0.1 on 2022-01-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0005_alter_loty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kraju', models.CharField(max_length=32)),
                ('kontynent', models.CharField(max_length=32)),
            ],
        ),
    ]
