# Generated by Django 4.0.1 on 2022-01-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0006_kraje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kraje',
            options={'verbose_name': 'Kraj', 'verbose_name_plural': 'Kraje'},
        ),
        migrations.AddField(
            model_name='loty',
            name='kraj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loty.kraje'),
        ),
    ]
