# Generated by Django 4.0.1 on 2022-01-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0007_alter_kraje_options_loty_kraj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_linii', models.CharField(max_length=32)),
                ('rodzaj_linii', models.CharField(choices=[('', ''), ('niskokosztowa', 'Niskokosztowa'), ('tradycyjna', 'Tradycyjna'), ('czarterowa', 'Czarterowa')], default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='loty',
            name='linia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loty.linie'),
        ),
    ]
