# Generated by Django 4.0.1 on 2022-01-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0008_linie_loty_linia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linie',
            options={'verbose_name': 'Linia', 'verbose_name_plural': 'Linie'},
        ),
        migrations.AlterField(
            model_name='linie',
            name='rodzaj_linii',
            field=models.CharField(blank=True, choices=[('', ''), ('niskokosztowa', 'Niskokosztowa'), ('tradycyjna', 'Tradycyjna'), ('czarterowa', 'Czarterowa')], default='', max_length=32, null=True),
        ),
    ]
