# Generated by Django 4.0.1 on 2022-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0010_alter_kraje_kontynent_alter_loty_data_lotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loty',
            name='data_lotu',
            field=models.DateField(),
        ),
    ]
