# Generated by Django 4.0.1 on 2022-02-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0011_alter_loty_data_lotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linie',
            name='rodzaj_linii',
            field=models.CharField(choices=[('', ''), ('niskokosztowa', 'Niskokosztowa'), ('tradycyjna', 'Tradycyjna'), ('czarterowa', 'Czarterowa')], default='', max_length=32),
        ),
    ]
