# Generated by Django 4.0.1 on 2022-03-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loty', '0012_alter_linie_rodzaj_linii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kraje',
            name='kontynent',
            field=models.CharField(choices=[('', ''), ('europa', 'Europa'), ('azja', 'Azja'), ('afryka', 'Afryka'), ('ameryka południowa', 'Ameryka Południowa'), ('australia', 'Australia'), ('ameryka północna', 'Ameryka Północna')], default='', max_length=32),
        ),
    ]
